### ISSUE TITLE
Default argument to wkhtmltopdf throws error with homebrew version

### ISSUE THREAD

**Issue by nmarley** [jjclark1982/metalsmith-pdf#1]
Is there some way to _not_ default to using the --print-media-type flag at all?

```
$ ./node_modules/metalsmith/bin/metalsmith
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: The switch --print-media-type, is not support using unpatched qt, and will be ignored.
    at Socket.<anonymous> (/Users/[...]/node_modules/metalsmith-pdf/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
```

The `metalsmith.json` file:

```
cat metalsmith.json
{
  "source": "rendered",
  "plugins": {
    "metalsmith-pdf": {
      "pattern": "**/*.html"
    }
  }
}
```

**Comment by jjclark1982** [comment]
I have removed the `printMediaType` default in version 1.2.0, which should prevent sending that switch.

I am unable to reproduce this error, so please check out the latest version and let me know how it works for you.

**Comment by nmarley** [comment]
I have no idea how to build & test this from the repo — I only know how to run it as above.

**Comment by jjclark1982** [comment]
I published it to npm, so you can get it by running

```
npm install metalsmith-pdf@1.2.0
```

**Comment by nmarley** [comment]
Looks like it worked! Thanks for the fix!

```
Metalsmith · successfully built to /.../build
```
